import { Inter } from 'next/font/google'
import './globals.css'
import './layout.css'
import Link from "next/link";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function LogoUserSearchButton(){
    return(
        <table className={"logo-userButton"}>
            <tr>
                <td>
                    <img className={"logo-img"} src={"/logo.png"}></img>
                </td>
                <td>
                    <div className={"main-img-wrapper"}>
                        <img src={"/search-button.png"}></img>
                        <img className={"user-profile"} src={"/user.png"}></img>

                    </div>
                </td>
            </tr>
        </table>
    )
}
function NavBar(){
    return (
        <div className={"nav-bar"}>
            <div>About</div>
            <Link href={'/board/movie'}>
            <div>Movie</div>
            </Link>
            <div>Film Universe</div>
            <div>Critic</div>
        </div>
    );
}

function DefaultLayout(){

  return (
      <div className={"layout-background"}>
          <LogoUserSearchButton></LogoUserSearchButton>
          <NavBar></NavBar>
      </div>
  )

}


function Footer(){
    return(
        <div className={"footer"}>
            <div className={"footer-content"}>
                <img className={"footer-img"} src={"/footerLogo.png"}></img>
                <div className={"footer-info"}>
                    <p>필름덤즈 대표자 : 허창훈 </p>
                    <p>등록번호 : 273-92-01709</p>
                    <p>등록일 :  2022.12.01  </p>
                    <p>문의 및 제안 : Filmdomaypole@naver.com</p>
                </div>
                <div className={"footer-link"}>
                    <Link href={"/"}>About us</Link>
                    <Link href={"/"}>Advertisement</Link>
                    <Link href={"/"}>Follow us</Link>
                </div>
                <div className={"footer-copyright"}>
                    <p className={"footer-copyright-text"}>Copyright Filmdom’s Rights All Reserved</p>
                    <div style={{marginTop:"20px",}} className={"footer-external"}>
                        <Link href={"https://www.instagram.com/filmdomaypole/"}>
                            <img style={{height:"18px", width:"18px",marginBottom:"3px",marginRight:"12px",opacity:"0.5"}}src="/instagram.png"/>
                        </Link>
                        <Link href={"/"}>
                            <img style={{height:"24px", width:"24px"}}src="/thread.png"/>
                        </Link>

                    </div>
                </div>
            </div>

        </div>
    )
}





export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <DefaultLayout></DefaultLayout>
      {children}
      <Footer></Footer>
      </body>
    </html>
  )
}
